version: '3'
services:
  imgproxy:
    container_name: 'imgproxy_backend'
    image: 'darthsim/imgproxy'
    restart: always
    environment:
      - IMGPROXY_KEY=943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881
      - IMGPROXY_SALT=943b421c9eb07c830af81030552c86009268de4e532ba2ee2eab8247c6da0881
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_ENABLE_CLIENT_HINTS=true
      - IMGPROXY_MAX_ANIMATION_FRAMES=30
      - IMGPROXY_TTL=31557600
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_PNG_INTERLACED=true
      - IMGPROXY_PNG_QUANTIZE=true
      - IMGPROXY_CONCURRENCY=16
      - IMGPROXY_QUALITY=85
      - IMGPROXY_GZIP_COMPRESSION=7
    ports:
      - '1314:8080'
  nginx:
    image: nginx:latest
    container_name: 'imgproxy_nginx'
    volumes:
      - ./conf:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443